name: "kubewarden-policy-build-rust"
description: "Build a rust policy using rust"
branding:
  icon: "package"
  color: "blue"
inputs:
  generate-sbom:
    required: false
    description: "Generate and sign SBOM files"
    # Boolean input should be compared with string
    # until https://github.com/actions/runner/issues/2238 resolved
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Prepare Rust environment
      shell: bash
      run: |
        rustup toolchain install stable  --profile minimal --target wasm32-wasip1
        rustup override set stable
    - name: Build Wasm module
      shell: bash
      run: cargo build --target=wasm32-wasip1 --release
    - name: Rename Wasm module
      shell: bash
      run: |
        cp target/wasm32-wasip1/release/*.wasm policy.wasm
    - name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm
    - name: Generate the SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        syft scan --output spdx-json=policy-sbom.spdx.json \
          --source-name $(yq '.annotations["io.kubewarden.policy.title"] + "-" + .annotations["io.kubewarden.policy.version"]' metadata.yml) \
          --source-version ${{ github.sha }} \
          -vv dir:.

    - name: Sign BOM file
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        cosign sign-blob --yes \
          --bundle policy-sbom.json.bundle.sigstore \
          policy-sbom.spdx.json
    - name: Upload policy SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.json.bundle.sigstore
