name: Tests and linters

on:
  workflow_call:
    inputs:
      policy-working-dir:
        description: "working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: .
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25"

      - name: run Go unit tests
        working-directory: ${{ inputs.policy-working-dir }}
        run: make test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v4.5.12
      - name: Build and annotate policy
        with:
          generate-sbom: false
          working-directory: ${{ inputs.policy-working-dir }}
        uses: kubewarden/github-actions/policy-build-tinygo@v4.5.12
      - name: Run e2e tests
        working-directory: ${{ inputs.policy-working-dir }}
        run: make e2e-tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25"
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        working-directory: ${{ inputs.policy-working-dir }}
        with:
          version: "latest"
